@WordWarrior_HostAddress = http://localhost:5201

GET {{WordWarrior_HostAddress}}/random-sentence/
Accept: application/json

###

POST {{WordWarrior_HostAddress}}/sentence/
Content-Type: application/json

{
  "content": "Mijn tweede zin"
}